#pragma once
// class boomerang
#define BOOMERANG_GRAVITY					0.015f

#define STATE_BOOMERANG_HIDEN				100
#define STATE_BOOMERANG_FLYING_RIGHT		200
#define STATE_BOOMERANG_FLYING_LEFT			300
#define STATE_BOOMERANG_DISPLAY				400

#define STATE_BOOMERANG_FLYING_ONE_TIME		1200
#define STATE_BOOMERANG_FLYING_TWO_TIME		2000
#define STATE_BOOMERANG_FLYING_THREE_TIME	3000

#define BOOMERANG_BBOX_WIDTH				15
#define BOOMERANG_BBOX_HEIGHT				16
#define BOOMERANG_FLYING_SPEECH				0.08f

#define BOOMERANG_SPEED_X_PLUS				0.05f
#define BOOMERANG_SPEED_Y_PLUS				0.01f

#define ANI_BOOMERANG_FLYING				0
#define ANI_BOOMERANG_DISPLAY				1

// class boomerang bros
#define BOOMERANG_WALKING_SPEED					0.02f
#define BOOMERANGBRO_GRAVITY					0.0005f

#define BOOMERANGBRO_BBOX_WIDTH					16
#define BOOMERANGBRO_BBOX_HEIGHT				24

#define STATE_BOOMERANGBRO_WALKING				100
#define STATE_BOOMERANGBRO_THROWING				200
#define STATE_BOOMERANGBRO_DIE					300

#define ANI_BOOMERANGBRO_WALKING_LEFT			0
#define ANI_BOOMERANGBRO_WALKING_RIGHT			1
#define ANI_BOOMERANGBRO_THROWING_LEFT			2
#define ANI_BOOMERANGBRO_THROWING_RIGHT			3	
#define ANI_BOOMERANGBRO_DIE_LEFT				4
#define ANI_BOOMERANGBRO_DIE_RIGHT				5

#define BOOMERANGBRO_BOOMERANG_LEFT_X			8		
#define BOOMERANGBRO_BOOMERANG_LEFT_Y			8
#define BOOMERANGBRO_BOOMERANG_RIGHT_X			14
#define BOOMERANGBRO_BOOMERANG_RIGHT_Y			8
#define BOOMERANGBRO_SHOOT_TIME 1500
#define BOOMERANGBRO_START_SHOOT_TIME 6000
#define BOOMERANGBRO_SHOOT_START_TIME 8000

#define BOOMERANGBRO_THROWN_BOOMERANG_TIME		4000
#define BOOMERANGBRO_RESET						4400

#define BOOMERANGBRO_RANGE_ATTACK_PLAYER_LEFT	-1
#define BOOMERANGBRO_RANGE_ATTACK_PLAYER_RIGHT	18

#define BOOMERANG_AMOUNT		1

