#pragma once

#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_KOOPAS	2
#define OBJECT_TYPE_GOOMBA	3
#define OBJECT_TYPE_NUMBER	24
#define OBJECT_TYPE_HUB	21
#define OBJECT_TYPE_HUB_TIME	23


#define OBJECT_TYPE_PORTAL	50

#define GRID_CELL_WIDTH 200
#define GRID_CELL_HEIGHT 200