#pragma once

// object type in loadphayscence
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_KOOPAS	2
#define OBJECT_TYPE_GOOMBA	3
#define OBJECT_TYPE_NUMBER	24
#define OBJECT_TYPE_HUB		21
#define OBJECT_TYPE_HUB_TIME 23
#define OBJECT_TYPE_LIST_SCORE			25
#define OBJECT_TYPE_SCORE			26

#define OBJECT_TYPE_HUB_ARROW					27
#define OBJECT_TYPE_HUB_ARROWS					28
#define OBJECT_TYPE_HUB_COIN 29
#define OBJECT_TYPE_HUB_LIVES 30
#define OBJECT_TYPE_HUB_GOALCARDS				32
#define OBJECT_TYPE_HUB_CARD				34

#define OBJECT_TYPE_HUB_CARDTEXT				35
#define OBJECT_TYPE_HUB_CARDTEXT				35
#define OBJECT_TYPE_TAIL	41

#define GRID_CELL_WIDTH 200
#define GRID_CELL_HEIGHT 200

// object type in grid 
#define OBJECT_TYPE_ROAD	2
#define OBJECT_TYPE_QUESTION_BRICK	4
#define OBJECT_TYPE_BORDER_ROAD	13
#define OBJECT_TYPE_WOOD_BLOCK	7
#define OBJECT_TYPE_PIPE	8
#define OBJECT_TYPE_BRICK_MANY_WALL	9


// object type question brick in grid 
#define OBJECT_TYPE_COIN 11
#define OBJECT_TYPE_MUSHROOM 18
#define OBJECT_TYPE_LEAF 19


