#pragma once

// object type in loadphayscence
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_KOOPAS	2
#define OBJECT_TYPE_KOOPAS_HAMMER	210


#define OBJECT_TYPE_GOOMBA	3
#define OBJECT_TYPE_NUMBER	24
#define OBJECT_TYPE_HUB		21
#define OBJECT_TYPE_HUB_TIME 23
#define OBJECT_TYPE_LIST_SCORE			25
#define OBJECT_TYPE_SCORE			26

#define OBJECT_TYPE_HUB_ARROW					27
#define OBJECT_TYPE_HUB_ARROWS					28
#define OBJECT_TYPE_HUB_COIN 29
#define OBJECT_TYPE_HUB_LIVES 30
#define OBJECT_TYPE_HUB_GOALCARDS				32
#define OBJECT_TYPE_HUB_CARD				34

#define OBJECT_TYPE_HUB_CARDTEXT				35
#define OBJECT_TYPE_HUB_CARDTEXT				35
#define OBJECT_PIECE_BRICK 36
#define OBJECT_TYPE_TAIL	41

#define GRID_CELL_WIDTH 200
#define GRID_CELL_HEIGHT 200

// object type in grid 
#define OBJECT_TYPE_ROAD	2
#define OBJECT_TYPE_QUESTION_BRICK	4
#define OBJECT_TYPE_BORDER_ROAD	13
#define OBJECT_TYPE_WOOD_BLOCK	7
#define OBJECT_TYPE_PIPE	8
#define OBJECT_TYPE_BRICK_MANY_WALL	9
#define OBJECT_TYPE_BRICK_COLISION 90

// object type question brick in grid 
#define OBJECT_TYPE_COIN 11
#define OBJECT_TYPE_MARIO_FIRE_BULLET 15
#define OBJECT_TYPE_FIRE_PLANT 16
#define OBJECT_TYPE_FIRE_BULLET 17
#define OBJECT_TYPE_PIRANHA_PLANT 22

#define OBJECT_TYPE_MUSHROOM 18
#define OBJECT_TYPE_LEAF 19
#define OBJECT_TYPE_BLUE_BRICK				20
#define OBJECT_TYPE_SWITCH_P					31
#define OBJECT_TYPE_BOOMERANG_BRO			38
#define OBJECT_TYPE_BOOMERANG				39
// 
#define BRICK_AMOUNT 20

#define ITEM_IN_BRICK_AMOUNT 20

