#pragma once

// *** playsecene ***
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_MAPBACKGROUND 7
#define SCENE_SECTION_GRID_RESOURCE 8

// *** grid ***
#define  GRID_RESOURCE_OBJECT_ITEM  1
#define  GRID_RESOURCE_ENEMIES  2
#define  GRID_RESOURCE_INITIAL  3


#define OBJECT_TYPE_MARIO	0


#define MAX_SCENE_LINE 1024

// hub
